### ISSUE TITLE
Create section8 part html & css (class="curriculum")

### ISSUE THREAD

**Issue by jjhstoday** [HaJunRyu/CafeW#18]
Create section8 part html & css (class="curriculum")

**Comment by HaJunRyu** [comment]
넵 pr후 말씀해주세요

**Comment by HaJunRyu** [comment]
1. html 227번 라인 em도 맞는거 같고 mark도 괜찮은거 같아요 참고만 하시고 결정은 지혜님이 :)

2. 현재 image들의 파일 이름이 07 10, Vector 이런식으로 되어있는걸 적절한 이름으로 변경해주세요.
예) 07.png -> curriculum-background.png

3. hover시 버그 수정 부탁드릴게요!

@jjhstoday
