### ISSUE TITLE
nav영역 정렬 수정

### ISSUE THREAD

**Issue by HaJunRyu** [HaJunRyu/CafeW#8]
1920px이상의 뷰포트에서 보니 header영역은 flex로 center처리하셔서 뷰포트 따라 자동으로 가운데 정렬이 잘 되는데 nav영역은 아마 다른 방법으로 정렬을 하셔서 크기가 다른 뷰포트에서는 다르게 보이는 증상이 있습니다. 수정 후 pull request부탁드려요 :)
@jjhstoday

**Comment by dev-junn** [comment]
ok

**Comment by jjhstoday** [comment]
네 확인했습니다!

**Comment by HaJunRyu** [comment]
@jjhstoday 
늦게 말씀드려서 죄송해요 추가로 검색버튼(돋보기 모양)에 cursor:pointer를 넣어주면 좋을거 같아요 이건 간단한 작업이니 내일 시간나실때 해서 올려주셔도 될거같습니다.

- 수정해주신 nav영역은 확인했습니다. header와 동일하게 잘 움직이네요 :) cursor까지 작업한걸 올려주시면 그때 merge진행하겠습니다.
